-- ============================================================================
-- TICKET-ADV007 - Convert trades to monthly range partitioning on trade_date
--
-- This script preserves any existing trade and settlement rows.
-- PostgreSQL requires the partition key in a partitioned table's primary key,
-- so settlements also stores trade_date for its composite foreign key.
-- ============================================================================

-- 1. Prepare settlements to reference the composite trades key.
ALTER TABLE settlements
    DROP CONSTRAINT IF EXISTS fk_settlements_trade;

ALTER TABLE settlements
    ADD COLUMN trade_date DATE;

UPDATE settlements AS s
SET trade_date = t.trade_date
FROM trades AS t
WHERE s.trade_id = t.id
  AND s.trade_date IS NULL;

ALTER TABLE settlements
    ALTER COLUMN trade_date SET NOT NULL;

-- 2. Preserve the original table while the partitioned replacement is built.
ALTER TABLE trades RENAME TO trades_legacy;

-- 3. Create the partitioned parent.
CREATE TABLE trades_partitioned (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trade_ref       VARCHAR(30)   NOT NULL,
    instrument_id   BIGINT        NOT NULL,
    counterparty_id BIGINT        NOT NULL,
    asset_class     VARCHAR(20)   NOT NULL,
    side            VARCHAR(4)    NOT NULL,
    quantity        NUMERIC(18,4) NOT NULL,
    price           NUMERIC(18,4) NOT NULL,
    trade_date      DATE          NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at     TIMESTAMPTZ,

    CONSTRAINT pk_trades
        PRIMARY KEY (id, trade_date),
    CONSTRAINT uq_trades_trade_ref_date
        UNIQUE (trade_ref, trade_date),
    CONSTRAINT fk_trades_instrument
        FOREIGN KEY (instrument_id) REFERENCES instruments(id),
    CONSTRAINT fk_trades_counterparty
        FOREIGN KEY (counterparty_id) REFERENCES counterparties(id)
) PARTITION BY RANGE (trade_date);

-- 4. Create April through July 2026 partitions plus a default catch-all.
CREATE TABLE trades_y2026m04 PARTITION OF trades_partitioned
    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');

CREATE TABLE trades_y2026m05 PARTITION OF trades_partitioned
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');

CREATE TABLE trades_y2026m06 PARTITION OF trades_partitioned
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

CREATE TABLE trades_y2026m07 PARTITION OF trades_partitioned
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE TABLE trades_default PARTITION OF trades_partitioned DEFAULT;

-- 5. Copy any existing rows. PostgreSQL routes each row to its partition.
INSERT INTO trades_partitioned (
    id,
    trade_ref,
    instrument_id,
    counterparty_id,
    asset_class,
    side,
    quantity,
    price,
    trade_date,
    status,
    deleted_at,
    created_at,
    modified_at
)
SELECT
    id,
    trade_ref,
    instrument_id,
    counterparty_id,
    asset_class,
    side,
    quantity,
    price,
    trade_date,
    status,
    deleted_at,
    created_at,
    modified_at
FROM trades_legacy;

-- 6. Advance the new identity sequence beyond the largest copied id.
SELECT setval(
    pg_get_serial_sequence('trades_partitioned', 'id'),
    COALESCE((SELECT MAX(id) FROM trades_partitioned), 1),
    EXISTS (SELECT 1 FROM trades_partitioned)
);

-- 7. Replace the legacy table with the partitioned parent.
DROP TABLE trades_legacy;
ALTER TABLE trades_partitioned RENAME TO trades;

-- 8. Create indexes on the parent; PostgreSQL creates matching child indexes.
CREATE INDEX idx_trades_trade_date
    ON trades (trade_date);

CREATE INDEX idx_trades_status
    ON trades (status);

CREATE INDEX idx_trades_instrument_id
    ON trades (instrument_id);

CREATE INDEX idx_trades_counterparty_id
    ON trades (counterparty_id);

-- 9. Restore settlement referential integrity using the composite key.
ALTER TABLE settlements
    ADD CONSTRAINT fk_settlements_trade
    FOREIGN KEY (trade_id, trade_date)
    REFERENCES trades (id, trade_date);

-- Verification:
-- \d+ trades
-- EXPLAIN ANALYZE
-- SELECT * FROM trades WHERE trade_date = DATE '2026-06-15';
